---
# tasks file for instance.docker
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
- name: Install Docker apt key.
  apt_key:
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_id }}"

- name: Create the apt sources file.
  copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt cache.
  apt:
    update_cache: yes

- name: Install Docker.
  apt:
    name: "docker-engine"
    state: present

- name: Create systemd Docker service directory.
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  register: docker_service_register

- name: Configure Docker storage.
  template:
    src: storage.conf.j2
    dest: /etc/systemd/system/docker.service.d/storage.conf
    mode: 0644
  register: docker_storage_register

- name: Reload Systemd.
  command: systemctl daemon-reload

- name: Restart Docker.
  service:
    name: docker
    state: restarted
  when: docker_storage_register.changed or docker_service_register.changed

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
