---
# kubernetes.yml
#
# This playbook deploys an OpenVPN server, a cfssl certificate instance, and a full Kubernetes cluster, integrated with AWS.
# It is based on the `kubes` terraform.
#

# Intial configuration Kubernetes instances
# Initial raw configuration
- hosts: cfssl
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python

# Configure CFSSL
- hosts: cfssl
  become: yes
  gather_facts: yes
  user: ubuntu
  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.hosts
    - role: instance.volume
    - role: instance.docker
    - role: instance.cfssl
    - role: instance.prometheus_node_exporter
