---
# wordpress_simple.yml
# ansible-playbook -i inventory/ec2.py wordpress_simple.yml 

# Initial raw configuration
- hosts: "tag_Name*wordpress*"
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python

# Configure openvpn instance (skipped if not created)
- hosts: "*wordpress*"
  become: yes
  gather_facts: yes
  remote_user: ubuntu
  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.hosts
    - role: instance.docker
    - role: instance.wordpress

